//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mAgicTVViewerGT.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mAgicTVViewerGT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   適用(_A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_Apply {
            get {
                return ResourceManager.GetString("General_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   基本設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_BaseSetting {
            get {
                return ResourceManager.GetString("General_BaseSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_Cancel {
            get {
                return ResourceManager.GetString("General_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_Confirm {
            get {
                return ResourceManager.GetString("General_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   曜日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_DayOfWeek {
            get {
                return ResourceManager.GetString("General_DayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡張 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_Extend {
            get {
                return ResourceManager.GetString("General_Extend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィルター設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_FilterSetting {
            get {
                return ResourceManager.GetString("General_FilterSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィルター条件 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_FiltrateCriteria {
            get {
                return ResourceManager.GetString("General_FiltrateCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   金 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_Friday {
            get {
                return ResourceManager.GetString("General_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_Monday {
            get {
                return ResourceManager.GetString("General_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_Name {
            get {
                return ResourceManager.GetString("General_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいフィルター に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_NewFilter {
            get {
                return ResourceManager.GetString("General_NewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいフォルダー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_NewFolder {
            get {
                return ResourceManager.GetString("General_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_OK {
            get {
                return ResourceManager.GetString("General_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_Others {
            get {
                return ResourceManager.GetString("General_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   土 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_Saturday {
            get {
                return ResourceManager.GetString("General_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   標準 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_Standard {
            get {
                return ResourceManager.GetString("General_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_StartDate {
            get {
                return ResourceManager.GetString("General_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時間帯 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_StartTimeBand {
            get {
                return ResourceManager.GetString("General_StartTimeBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_Sunday {
            get {
                return ResourceManager.GetString("General_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   木 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_Thursday {
            get {
                return ResourceManager.GetString("General_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_Title {
            get {
                return ResourceManager.GetString("General_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   火 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_Tuesday {
            get {
                return ResourceManager.GetString("General_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未視聴 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_Unviewed {
            get {
                return ResourceManager.GetString("General_Unviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   視聴済み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_Viewed {
            get {
                return ResourceManager.GetString("General_Viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   視聴状況 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_ViewHistory {
            get {
                return ResourceManager.GetString("General_ViewHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   水 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string General_Wednesday {
            get {
                return ResourceManager.GetString("General_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   長さ(分) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_LengthMinute {
            get {
                return ResourceManager.GetString("Grid_LengthMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_StartDateTime {
            get {
                return ResourceManager.GetString("Grid_StartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   放送局 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_Station {
            get {
                return ResourceManager.GetString("Grid_Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_Title {
            get {
                return ResourceManager.GetString("Grid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ○ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grid_Viewed {
            get {
                return ResourceManager.GetString("Grid_Viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   番組の削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string List_DeleteProgram {
            get {
                return ResourceManager.GetString("List_DeleteProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未視聴にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string List_MakeUnviewed {
            get {
                return ResourceManager.GetString("List_MakeUnviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   視聴済みにする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string List_MakeViewed {
            get {
                return ResourceManager.GetString("List_MakeViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべて選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string List_SelectAll {
            get {
                return ResourceManager.GetString("List_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   視聴する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string List_View {
            get {
                return ResourceManager.GetString("List_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   100% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ribbon_100Percent {
            get {
                return ResourceManager.GetString("Ribbon_100Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ribbon_Enlarge {
            get {
                return ResourceManager.GetString("Ribbon_Enlarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡大/縮小 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ribbon_EnlargeReduce {
            get {
                return ResourceManager.GetString("Ribbon_EnlargeReduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ribbon_FileTab {
            get {
                return ResourceManager.GetString("Ribbon_FileTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ribbon_HomeTab {
            get {
                return ResourceManager.GetString("Ribbon_HomeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   縮小 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ribbon_Reduce {
            get {
                return ResourceManager.GetString("Ribbon_Reduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status_All {
            get {
                return ResourceManager.GetString("Status_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status_Filtered {
            get {
                return ResourceManager.GetString("Status_Filtered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィルターの新規作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Add {
            get {
                return ResourceManager.GetString("Tree_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダーの新規作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_AddFolder {
            get {
                return ResourceManager.GetString("Tree_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「その他」の新規作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_AddOthers {
            get {
                return ResourceManager.GetString("Tree_AddOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Delete {
            get {
                return ResourceManager.GetString("Tree_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Edit {
            get {
                return ResourceManager.GetString("Tree_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべての番組 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_TopItem {
            get {
                return ResourceManager.GetString("Tree_TopItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉じる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Window_Close {
            get {
                return ResourceManager.GetString("Window_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Window_Help {
            get {
                return ResourceManager.GetString("Window_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   録画フォルダーを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Window_OpenFolder {
            get {
                return ResourceManager.GetString("Window_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Window_VersionInfo {
            get {
                return ResourceManager.GetString("Window_VersionInfo", resourceCulture);
            }
        }
    }
}
